export const subscriptionPlans = {
  free: {
    id: "free",
    name: "Free",
    description: "Access to Indian news only",
    price: 0,
    currency: "INR",
    interval: "month",
    features: [
      "Unlimited access to Indian news",
      "Basic news categories",
      "Standard support",
      "Ad-supported experience",
    ],
    buttonText: "Current Plan",
    buttonVariant: "outline",
    disabled: true,
    type: "FREE",
  },
  premium_monthly: {
    id: "premium_monthly",
    name: "Premium Monthly",
    description: "Full access to all news with monthly billing",
    price: 499,
    currency: "INR",
    interval: "month",
    features: [
      "Access to all Indian news",
      "Access to World news",
      "Premium news categories",
      "Priority support",
      "Ad-free experience",
      "Early access to new features",
    ],
    buttonText: "Subscribe Monthly",
    buttonVariant: "default",
    disabled: false,
    type: "PREMIUM",
  },
  premium_yearly: {
    id: "premium_yearly",
    name: "Premium Yearly",
    description: "Full access to all news with yearly billing (2 months free)",
    price: 4990,
    currency: "INR",
    interval: "year",
    features: [
      "All Premium Monthly features",
      "2 months free",
      "Priority customer support",
      "Exclusive content access",
      "Ad-free experience",
      "Early access to new features",
    ],
    buttonText: "Subscribe Yearly",
    buttonVariant: "default",
    disabled: false,
    type: "PREMIUM",
  },
};
